#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LottieDialogs.Android.Resource", IsApplication=false)]

namespace LottieDialogs.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public static int IsIndeterminate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public static int lottie_autoPlay = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int lottie_fileName = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int lottie_loop = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int roundedbg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int roundedbg_white = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int roundedbgdark = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public static int bottom_textViewStatus = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int center_textViewStatus = 2130968579;
			
			// aapt resource value: 0x7f040001
			public static int lottieAnimationView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int lottie_layer_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public static int top_textViewStatus = 2130968580;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int animation_only_progress_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int bottom_header_progress_dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int center_header_progress_dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int top_header_progress_dialog = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public static int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LottieAnimationView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public static int LottieAnimationView_lottie_autoPlay = 1;
			
			// aapt resource value: 0
			public static int LottieAnimationView_lottie_fileName = 0;
			
			// aapt resource value: 2
			public static int LottieAnimationView_lottie_loop = 2;
			
			public static int[] LottieProgressControl = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public static int LottieProgressControl_IsIndeterminate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
