#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LottieDialogs.Sample.Android.Resource", IsApplication=true)]

namespace LottieDialogs.Sample.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::LottieDialogs.Android.Resource.Attribute.IsIndeterminate = global::LottieDialogs.Sample.Android.Resource.Attribute.IsIndeterminate;
			global::LottieDialogs.Android.Resource.Attribute.lottie_autoPlay = global::LottieDialogs.Sample.Android.Resource.Attribute.lottie_autoPlay;
			global::LottieDialogs.Android.Resource.Attribute.lottie_fileName = global::LottieDialogs.Sample.Android.Resource.Attribute.lottie_fileName;
			global::LottieDialogs.Android.Resource.Attribute.lottie_loop = global::LottieDialogs.Sample.Android.Resource.Attribute.lottie_loop;
			global::LottieDialogs.Android.Resource.Drawable.roundedbg = global::LottieDialogs.Sample.Android.Resource.Drawable.roundedbg;
			global::LottieDialogs.Android.Resource.Drawable.roundedbgdark = global::LottieDialogs.Sample.Android.Resource.Drawable.roundedbgdark;
			global::LottieDialogs.Android.Resource.Id.lottieAnimationView = global::LottieDialogs.Sample.Android.Resource.Id.lottieAnimationView;
			global::LottieDialogs.Android.Resource.Id.lottie_layer_name = global::LottieDialogs.Sample.Android.Resource.Id.lottie_layer_name;
			global::LottieDialogs.Android.Resource.Id.textViewStatus = global::LottieDialogs.Sample.Android.Resource.Id.textViewStatus;
			global::LottieDialogs.Android.Resource.Layout.animatedprogress = global::LottieDialogs.Sample.Android.Resource.Layout.animatedprogress;
			global::LottieDialogs.Android.Resource.String.ApplicationName = global::LottieDialogs.Sample.Android.Resource.String.ApplicationName;
			global::LottieDialogs.Android.Resource.String.Hello = global::LottieDialogs.Sample.Android.Resource.String.Hello;
			global::LottieDialogs.Android.Resource.Styleable.LottieAnimationView = global::LottieDialogs.Sample.Android.Resource.Styleable.LottieAnimationView;
			global::LottieDialogs.Android.Resource.Styleable.LottieAnimationView_lottie_autoPlay = global::LottieDialogs.Sample.Android.Resource.Styleable.LottieAnimationView_lottie_autoPlay;
			global::LottieDialogs.Android.Resource.Styleable.LottieAnimationView_lottie_fileName = global::LottieDialogs.Sample.Android.Resource.Styleable.LottieAnimationView_lottie_fileName;
			global::LottieDialogs.Android.Resource.Styleable.LottieAnimationView_lottie_loop = global::LottieDialogs.Sample.Android.Resource.Styleable.LottieAnimationView_lottie_loop;
			global::LottieDialogs.Android.Resource.Styleable.LottieProgressControl = global::LottieDialogs.Sample.Android.Resource.Styleable.LottieProgressControl;
			global::LottieDialogs.Android.Resource.Styleable.LottieProgressControl_IsIndeterminate = global::LottieDialogs.Sample.Android.Resource.Styleable.LottieProgressControl_IsIndeterminate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int IsIndeterminate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int lottie_autoPlay = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int lottie_fileName = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int lottie_loop = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int roundedbg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int roundedbgdark = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040004
			public const int MyButton = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int MyProgressControl = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int lottieAnimationView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int lottie_layer_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int textViewStatus = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int animatedprogress = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LottieAnimationView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int LottieAnimationView_lottie_autoPlay = 1;
			
			// aapt resource value: 0
			public const int LottieAnimationView_lottie_fileName = 0;
			
			// aapt resource value: 2
			public const int LottieAnimationView_lottie_loop = 2;
			
			public static int[] LottieProgressControl = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int LottieProgressControl_IsIndeterminate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
